openapi: "3.0.0"
info:
  title: CodeBS Chat App
  description: CodeBS 채팅 웹 어플리케이션 - API 명세
  version: 0.1.0

servers:
  - url: http://localhost:3000
    description: Local

paths:
  /chat/room/{userId}:
    get:
      summary: 유저가 입장해 있는 방 모두 반환
      tags: [Chat]
      parameters:
        - in: header
          name: access_token
          schema:
            type: string
          description: JWT 토큰
        - in: path
          name: userId
          schema:
            type: string
          required: true
          description: 로그인 아이디
      responses:
        "200":
          description: 모든 방 목록
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/room"
  /chat/room:
    post:
      summary: 새로운 방 생성
      tags: [Chat]
      parameters:
        - in: header
          name: access_token
          schema:
            type: string
          description: JWT 토큰
      requestBody:
        description: Request Body 정의
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createroom"
      responses:
        "200":
          description: 생성한 방 정보
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/room"
  /chat/room/enter/{roomId}:
    get:
      summary: 방 고유 번호가 roomId 인 방에 입장
      tags: [Chat]
      parameters:
        - in: header
          name: access_token
          schema:
            type: string
          description: JWT 토큰
        - in: path
          name: roomId
          schema:
            type: string
          required: true
          description: 방 고유 번호
      responses:
        200:
          description: 입장한 방 id와 채팅 기록 배열
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: "#/components/schemas/user"
                  chatHistory:
                    $ref: "#/components/schemas/chatHistory"
  /chat/room/invites/{userId}:
    get:
      summary: 받은 채팅방 초대 목록 가져오기
      tags: [Chat]
      parameters:
        - in: header
          name: access_token
          schema:
            type: string
          description: JWT 토큰
        - in: path
          name: userId
          schema:
            type: string
          required: true
          description: 로그인 아이디
      responses:
        200:
          description: 초대 받은 방 목록
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/room"
  /chat/room/join:
    post:
      summary: 방 초대 승락
      tags: [Chat]
      parameters:
        - in: header
          name: access_token
          schema:
            type: string
          description: JWT 토큰
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: 로그인 아이디
                roomId:
                  type: string
                  description: 방 고유 아이디
      responses:
        200:
          description: 입장 성공
  /auth/login:
    post:
      summary: 로그인
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: 로그인 아이디
                password:
                  type: string
                  description: 패스워드
      responses:
        200:
          description: 로그인 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: "#/components/schemas/user"
                  accessToken:
                    type: string
  /auth/logout:
    get:
      summary: 로그아웃
      tags: [Auth]
      responses:
        200:
          description: 로그아웃 성공
  /auth:
    post:
      summary: 회원가입
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/newuser"
      responses:
        200:
          description: 회원 가입 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
  /auth/refresh_token:
    get:
      summary: token 재 발급
      tags: [Auth]
      responses:
        200:
          description: token 재 발급 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: brand new token
  /user/{userId}:
    get:
      summary: 유저 검색
      tags: [User]
      parameters:
        - in: header
          name: access_token
          schema:
            type: string
          description: JWT 토큰
        - in: path
          name: userId
          schema:
            type: string
          required: true
          description: 검색하는 유저 아이디
      responses:
        200:
          description: 유저 검색 결과
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user"
  /user/friend:
    post:
      summary: 친구 추가
      tags: [User]
      parameters:
        - in: header
          name: access_token
          schema:
            type: string
          description: JWT 토큰
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: 본인 로그인 아이디
                friendId:
                  type: string
                  description: 추가하고자 하는 유저 로그인 아이디
      responses:
        200:
          description: 친구 추가 성공
  /user/friend/{userId}:
    get:
      summary: 친구 목록
      tags: [User]
      parameters:
        - in: header
          name: access_token
          schema:
            type: string
          description: JWT 토큰
        - in: path
          name: userId
          schema:
            type: string
          required: true
          description: 유저 로그인 아이디
      responses:
        200:
          description: 친구 목록
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user"
  /user/friend_req/{userId}:
    get:
      summary: 친구 요청 목록
      tags: [User]
      parameters:
        - in: header
          name: access_token
          schema:
            type: string
          description: JWT 토큰
        - in: path
          name: userId
          schema:
            type: string
          required: true
          description: 유저 로그인 아이디
      responses:
        200:
          description:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user"
  /user/avatar:
    put:
      summary: 프로필 사진 변경
      tags: [User]
      parameters:
        - in: header
          name: access_token
          schema:
            type: string
          description: JWT 토큰
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: 본인 로그인 아이디
                avatarUrl:
                  type: string
                  description: 이미지 URL
      responses:
        200:
          description: 변경 성공
  /user/status_message:
    put:
      summary: 상태 메세지 변경
      tags: [User]
      parameters:
        - in: header
          name: access_token
          schema:
            type: string
          description: JWT 토큰
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: 본인 로그인 아이디
                statusMessage:
                  type: string
                  description: 변경할 상태 메세지
      responses:
        200:
          description: 변경 성공
components:
  schemas:
    room:
      type: object
      properties:
        _id:
          type: string
        roomName:
          type: string
        regDate:
          type: string
        masterUserId:
          type: string
        chatHistory:
          $ref: "#/components/schemas/chatHistory"
    user:
      type: object
      properties:
        userId:
          type: string
          description: 로그인 아이디
        nickname:
          type: string
          description: 닉네임
        avatarUrl:
          type: string
          description: 프사
        statusMessage:
          type: string
          description: 상태 메세지
    createroom:
      type: object
      properties:
        roomName:
          type: string
          description: 사용자가 입력한 방 이름
        userId:
          type: string
          description: 요청한 유저의 고유 번호
    chatHistory:
      type: array
      items:
        type: object
        properties:
          _id:
            type: string
            description: 채팅 로그 고유 번호
          message:
            type: string
            description: 채팅 메시지 내용
          regDate:
            type: string
            description: 등록일
          userId:
            type: string
            description: 유저 아이디
          nickname:
            type: string
            description: 유저 닉네임
          avatarUrl:
            type: string
            description: 프사
          statusMessage:
            type: string
            description: 상태 메세지
    newuser:
      type: object
      properties:
        userId:
          type: string
          description: 로그인 아이디
        password:
          type: string
          description: 로그인 패스워드
        nickname:
          type: string
          description: 닉네임
        avatarUrl:
          type: string
          description: 프사
        statusMessage:
          type: string
          description: 상태 메세지
    friendList:
      type: array
      items:
        $ref: "#/components/schemas/user"
