openapi: "3.0.0"
info:
  title: CodeBS Chat App
  description: CodeBS 채팅 웹 어플리케이션 - API 명세
  version: 0.1.0

servers:
  - url: http://localhost:3000
    description: Local

paths:
  /chat/room:
    get:
      summary: 모든 방 목록을 반환
      tags: [Chat]
      responses:
        "200":
          description: 모든 방 목록
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/room"
    post:
      summary: 새로운 방 생성
      tags: [Chat]

      requestBody:
        description: Request Body 정의
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createroom"
      responses:
        "200":
          description: 생성한 방 정보
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/room"
  /chat/room/enter/{roomId}:
    get:
      summary: 방 고유 번호가 roomId 인 방에 입장
      tags: [Chat]
      parameters:
        - in: path
          name: roomId
          schema:
            type: string
          required: true
          description: 방 고유 번호
      responses:
        200:
          description: 입장한 방 id와 채팅 기록 배열
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    description: 방 고유 번호
                  chatHistory:
                    type: array
                    description: 채팅 기록

components:
  schemas:
    room:
      type: object
      properties:
        _id:
          type: string
        roomName:
          type: string
        regDate:
          type: string
        masterUserId:
          type: string
        chatHistory:
          $ref: "#/components/schemas/chatHistory"
    createroom:
      type: object
      properties:
        roomName:
          type: string
          description: 사용자가 입력한 방 이름
        userId:
          type: string
          description: 요청한 유저의 고유 번호
    chatHistory:
      type: array
      items:
        type: object
        properties:
          _id:
            type: string
            description: 채팅 로그 고유 번호
          message:
            type: string
            description: 채팅 메시지 내용
          regDate:
            type: string
            description: 등록일
          userId:
            type: string
            description: 유저 아이디
